on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

permissions:
  contents: write

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install System Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev \
                        libudunits2-dev \
                        libgdal-dev \
                        libgeos-dev \
                        libproj-dev \
                        libmysqlclient-dev \
                        libssl-dev

      - name: Put pandoc in PATH
        run: |
          mkdir -p ~/.local/bin
          ln -s $(dirname $(readlink -f  $(which quarto)))"/pandoc" ~/.local/bin/pandoc
        shell: bash

      - name: Set up R (needed for Rmd)
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up renv
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2

      - name: Build site 🔧
        run: |
          quarto render

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
